### ISSUE TITLE
Exception when using Credential Provider and signing commits

### ISSUE THREAD

**Issue by magneticflux-** [natanfudge/Cloak#17]
```
org.eclipse.jgit.api.errors.JGitInternalException: missing credentials provider
	at org.eclipse.jgit.lib.internal.BouncyCastleGpgSigner.sign(BouncyCastleGpgSigner.java:162)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:271)
	at cloak.git.CloakRepository.commit(CloakRepository.kt:70)
	at cloak.git.YarnRepo.commitChanges(YarnRepo.kt:139)
	at cloak.format.rename.Renamer.commitChanges(Renamer.kt:142)
	at cloak.format.rename.Renamer.applyRename(Renamer.kt:113)
	at cloak.format.rename.Renamer$rename$2$2.invokeSuspend(Renamer.kt:73)
	at cloak.format.rename.Renamer$rename$2$2.invoke(Renamer.kt)
	at cloak.idea.platformImpl.IdeaPlatform$asyncWithText$$inlined$suspendCoroutine$lambda$1$1.invokeSuspend(IdeaPlatform.kt:160)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at cloak.idea.platformImpl.IdeaPlatform$asyncWithText$$inlined$suspendCoroutine$lambda$1.run(IdeaPlatform.kt:160)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.bouncycastle.openpgp.PGPException: missing credentials provider
	at org.eclipse.jgit.lib.internal.BouncyCastleGpgKeyPassphrasePrompt.getPassphrase(BouncyCastleGpgKeyPassphrasePrompt.java:120)
	at org.eclipse.jgit.lib.internal.BouncyCastleGpgKeyLocator.findSecretKeyForKeyBoxPublicKey(BouncyCastleGpgKeyLocator.java:395)
	at org.eclipse.jgit.lib.internal.BouncyCastleGpgKeyLocator.findSecretKey(BouncyCastleGpgKeyLocator.java:292)
	at org.eclipse.jgit.lib.internal.BouncyCastleGpgSigner.locateSigningKey(BouncyCastleGpgSigner.java:124)
	at org.eclipse.jgit.lib.internal.BouncyCastleGpgSigner.sign(BouncyCastleGpgSigner.java:133)
	... 32 more
```

**Comment by natanfudge** [comment]
Hmm, I thought you don't need a credentials provider to sign commits. I guess it kind of makes sense, you could be impersonated.

**Comment by natanfudge** [comment]
I've made it so it uses the IDEA credentials manager, that should fix it. This comes with a nice side effect that you don't need to type out your username/email anymore. 
The update will take a while to get approved, so you would do me a big favor if you see if the issue is resolved [using the plugin jar](https://github.com/natanfudge/Cloak/blob/1.1/Cloak-1.1.1-all.jar) manually (in the plugins panel, select the cog and then "install from disk") .

**Comment by magneticflux-** [comment]
It looks like that fixed it, thanks for the quick response!

**Comment by natanfudge** [comment]
Nice
